title: My Blog
future: true
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  permalink: /page/:num/
  sort_field: 'date'
  sort_reverse: true
